name: Log ISS Location Data Daily

on: push

jobs:
  collect-iss-data:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: 23f2000237@ds.study.iitm.ac.in
        run: echo "Hello, world!"
